[project]
name = "ucla_plha"
version = "1.2.0"
description = "A code for performing probabilistic liquefaction hazard analysis inside the hazard integral"
authors = [
    {name = "Meera L. Kota"},
    {name = "Scott J. Brandenberg"}
    ]
license = "LICENSE"
readme = "README.md"

requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "importlib_resources",
    "jsonschema",
    "setuptools"
]

[tool.poetry.group.test.dependencies]
pytest = ">=7.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
